services:
- type: web
  name: comp
  plan: free
  repo: https://github.com/qaes26/comp
  branch: master
  rootDir: /
  buildCommand: npm install
  startCommand: npm start
  envVars:
  - key: NODE_VERSION
    value: 22.x
  # أمر التثبيت المسبق لأدوات النظام (g++ و python3)
  preBuild: sudo apt-get update && sudo apt-get install -y python3 g++